// This file serves as a module anchor for the schemas.
// The actual Rust code for protobuf messages is generated by `prost-build`
// in `build.rs` (located at the root of the `bitquery-solana-sdk` project)
// and included directly in `lib.rs` using:
// `include!(concat!(env!("OUT_DIR"), "/solana.rs"));`
// (assuming `package solana;` is used in the .proto file).

// This `mod.rs` file ensures that the directory `src/schemas/` is recognized as a module
// path, which can be helpful for `prost-build` if it needs to resolve relative paths
// for `import` statements within .proto files (though `solana.proto` currently has no imports).

// No public re-exports are typically needed here if the generated code is included
// directly into `lib.rs` or another central module. If `solana.rs` were included here, like:
//
//   pub mod generated {
//       include!(concat!(env!("OUT_DIR"), "/solana.rs"));
//   }
//   pub use generated::*;
//
// then this file would be more active. However, the common pattern is to include
// in `lib.rs` to make `crate::schemas::SolanaMessage` directly accessible.
