// This file serves as a module anchor for the schemas.
// The actual Rust code for protobuf messages is generated by `prost-build`
// in `build.rs` and included directly in `lib.rs` or another appropriate
// place using `include!(concat!(env!("OUT_DIR"), "/solana.rs"));`.
//
// This file being present allows `src/schemas/solana.proto` to be correctly
// referenced by `build.rs` using the `&["src/schemas/"]` include path.

// Optionally, you could re-export items from the generated module here if it were
// included into this `mod.rs` file instead of `lib.rs`, e.g.:
//
// pub mod solana {
//     include!(concat!(env!("OUT_DIR"), "/solana.rs"));
// }
// pub use solana::*;
//
// However, the current pattern in `lib.rs` is to include it there directly.
